# Generated by Django 3.2.5 on 2022-09-02 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('product_sn', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=20)),
                ('product_detail', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=200)),
                ('sn', models.CharField(max_length=20)),
                ('defects', models.CharField(max_length=100)),
                ('hazards', models.CharField(max_length=100)),
                ('consumers', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('traders', models.CharField(max_length=100)),
                ('sold_venues', models.CharField(max_length=100)),
                ('avaiable_sale_date', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.category')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
